/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;
import java.util.List;

import org.example.TrainMerger.Bogie;

public class App {
    
    public static void main(String[] args) {
        System.out.println("Welcome to Train App from Geektrust");

         // Example input: Bogies of Train A and Train B
        List<String> trainA = Arrays.asList("NDL", "SLM", "BPL", "AGA");
        List<String> trainB = Arrays.asList("GHY", "MAQ", "PNE", "SRR");

        // Step 1: Print the order of bogies at Hyderabad (Train A and Train B)
        System.out.println("Train A bogies at HYB: " + trainA);
        System.out.println("Train B bogies at HYB: " + trainB);

        // Step 2: Merge and sort the bogies based on distance from HYB
        List<Bogie> mergedBogies = TrainMerger.mergeAndSortBogies(trainA, trainB);

        // Step 3: Print the departure bogie order of Train AB from Hyderabad
        System.out.print("Train AB departure bogies from HYB: ");
        for (Bogie bogie : mergedBogies) {
            System.out.print(bogie.destination + " ");
        }
    }
}
